### ISSUE TITLE
Icon Issue

### ISSUE THREAD

**Issue by pyclasses** [tunitowen/fancy_bottom_navigation#10]
Look sharp. Icons are stuck

![screenshot_2019-01-11-21-52-29-676_com example voicesend 1](https://user-images.githubusercontent.com/34451016/51046250-93a3e380-15eb-11e9-9b4f-c5ff24cf8da5.png)

**Comment by tunitowen** [comment]
Ah, I see. So when you navigate away and then back the icon is wrong. Will fix.

**Comment by pyclasses** [comment]
Great work.

**Comment by tunitowen** [comment]
Fixed in 3.0.1, uploaded to pub, will be available soon.
