### ISSUE TITLE
Navigation Issue

### ISSUE THREAD

**Issue by pyclasses** [tunitowen/fancy_bottom_navigation#12]
Something going wrong. Look sharp.
![screenrecorder-2019-01-12-05-49-45-243 1](https://user-images.githubusercontent.com/34451016/51066316-6e38c900-162f-11e9-8ae4-c334da89e256.gif)

**Comment by TheWithz** [comment]
Can you post your call to the constructor

**Comment by pyclasses** [comment]
Now, it's work ### **Thanks** @TheWithz
