### ISSUE TITLE
white line as separator

### ISSUE THREAD

**Issue by Miolin** [tunitowen/fancy_bottom_navigation#17]
we can see the white line if we put a dark background.
![capture](https://user-images.githubusercontent.com/29582752/52177052-5edb1480-27c4-11e9-8ffb-d717db58adb5.PNG)
I changed one line and this has ceased to be a problem for me. 
I commented out a line in BoxDecoration, which assigned him a white
`
child: Container(
  width: CIRCLE_SIZE + CIRCLE_OUTLINE,
  height: CIRCLE_SIZE + CIRCLE_OUTLINE,
  decoration: BoxDecoration(
    //color: Colors.white,
    shape: BoxShape.circle,
    boxShadow: [
      BoxShadow(
        color: Colors.black12,
        blurRadius: 8)
])),
`

**Comment by tunitowen** [comment]
Thanks, I will review your PR and update.

**Comment by tunitowen** [comment]
Merged, will be in the next version

**Comment by jkoenig134** [comment]
Hi @tunitowen The problem still exists in my application, i cant use the dark mode. 
You have written it will be in the next version, but it isn´t merged yet. Could you do that?
