### ISSUE TITLE
Title not hide properly when in other language

### ISSUE THREAD

**Issue by jasonlaw** [tunitowen/fancy_bottom_navigation#29]
Any idea how to fix this?
![image](https://user-images.githubusercontent.com/107820/56480479-d891bd00-64ec-11e9-9443-e92145dba913.png)

**Comment by Robarelli** [comment]
This also happens when a user sets their system text size to something larger than the default. I've observed this on at least iOS devices

**Comment by brux88** [comment]
same problem

**Comment by pengjugame** [comment]
same problem

**Comment by jasonlaw** [comment]
Still waiting for the fix. Anyone here has any workaround for this?
