### ISSUE TITLE
Active Icon stuck

### ISSUE THREAD

**Issue by SimonHeimer** [tunitowen/fancy_bottom_navigation#3]
The active stucks on screen as active when entering diffrent pages.
![screenshot_1546990565](https://user-images.githubusercontent.com/43775077/50865596-a8436a00-13a6-11e9-9718-162d540e251c.png)

**Comment by tunitowen** [comment]
Thanks for raising. This will be due to the Overlay widget I used. I will look into this tomorrow and fix.

**Comment by tunitowen** [comment]
Pushed to master, and version 0.2.0 on pub. All should be fixed now
