### ISSUE TITLE
change page with material page route

### ISSUE THREAD

**Issue by DanialV** [tunitowen/fancy_bottom_navigation#30]
Is there any way to change tabs with Navigator I have multi scaffold page and I want to have the static bottom navigation in all my pages is this possible?

**Comment by tunitowen** [comment]
Hi, sorry for the huge delay. In theory, this exposes a tabChangedListener .. which you need to act on. And, because Flutter, its just a Widget .. So I would say its technically possible, but I don't have time to look into the method.
