### ISSUE TITLE
Flutter 3.0 Bugs Showing for a method.

### ISSUE THREAD

**Issue by Kayuemkhan** [tunitowen/fancy_bottom_navigation#70]
I upgraded flutter 3.0 Yesterday and got this line: 

```
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/fancy_bottom_navigation-0.3.3/lib/fancy_bottom_navigation.dart:111:7: Error: No named parameter with the name 'overflow'.
      overflow: Overflow.visible,
      ^^^^^^^^
```

**Comment by techcafe13** [comment]
In the new version of Flutter, Stack does not take overflow as parameter. go to the Package and go to the Stack widget most probably around line 109,

`overflow: Overflow.visible` should be changed to `clipBehavior: Clip.none` then everything will work fine

**Comment by rsbthebest** [comment]
Do we have a new version planned for this?

**Comment by JaccoVeldscholten** [comment]
Update would be nice.

**Comment by JagadishaIncture** [comment]
> In the new version of Flutter, Stack does not take overflow as parameter. go to the Package and go to the Stack widget most probably around line 109,
> 
> `overflow: Overflow.visible` should be changed to `clipBehavior: Clip.none` then everything will work fine

Worked

**Comment by Kayuemkhan** [comment]
@techcafe13 How can i do that ? It's from the library.

**Comment by techcafe13** [comment]
> @techcafe13 How can i do that ? It's from the library. 

Its already updated I think. Just update your package.

**Comment by Kayuemkhan** [comment]
@techcafe13 , Thanks a lot.
